# vim:ft=kitty
## name: Nord
## author: Eric N. Vander Weele
## upstream: https://www.nordtheme.com/
## blurb: Nord theme utilizing the full Frost and Aurora palette.

# Basic colors
foreground           #d8dee9
background           #2e3440
selection_foreground #d8dee9
selection_background #434c5e

# Cursor colors
cursor            #d8dee9
cursor_text_color #3b4252

# URL underline color when hovering with mouse
url_color #0087bd

# Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

# Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

# The basic 16 colors
# black
color0 #3b4252
color8 #4c566a

# red
color1 #bf616a
color9 #bf616a

# green
color2  #a3be8c
color10 #a3be8c

# yellow
color3  #ebcb8b
color11 #d08770

# blue
color4  #81a1c1
color12 #5e81ac

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #88c0d0
color14 #8fbcbb

# white
color7  #e5e9f0
color15 #eceff4

# opacidade e desfoque do terminal
background_opacity 1.0
background_blur 1

# avançado
term xterm-kitty

# sinal sonoro do terminal
enable_audio_bell no

# ajustes específicos do sistema operacional (decoração da janela Gnome para wayland)
linux_display_server x11

# fonte
font_family        JetBrainsMono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 12.0

# gerenciamento do tamanho da fonte
map ctrl+shift+backspace change_font_size all 0

# personalização do cursor
# bloco / feixe / sublinhado
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# histórico de rolagem
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# mouse
mouse_hide_wait -1

# layout da janela
remember_window_size  no
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# gerenciamento de janelas
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# gerenciamento de layout
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# personalização da barra de guias
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# gerenciamento de guias
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+w close_tab
